language: node_js
node_js:
    - "7"
branches:
    only:
        - master
before_script:
    - npm install -g firebase-tools
script:
    - echo "deploying"
after_success:
    - firebase deploy -- project pleasesleepwithme-c20ca --token $FIREBASE_TOKEN
